package org.zootella.furball.original;

public enum Tile {
	GRASS,		// LISTED FIRST TO HAVE THE VALUE 0
	FBONGRASS,
	FBONSINK,
	BOXONGRASS,
	BOXONSINK,
	ROCK,
	WALL,
	ENEMY,
	SINK,
	HEART,
	DOORCLOSED,
	DOOROPEN,
	OUTSIDE		// USED TO DESCRIBE A POSITION OFF THE BOARD
}
